FROM docker.io/maven:3.9.14-eclipse-temurin-11-alpine

MAINTAINER Christoph Kappel <christophl@unexist.dev>

RUN apk add --no-cache ruby doxygen python3 py3-pip plantuml git make
RUN gem install asciidoctor asciidoctor-rouge asciidoctor-diagram asciidoctor-multipage

#RUN pip3 install asciidoxy --break-system-packages
RUN git clone https://github.com/unexist/asciidoxy.git \
    && cd asciidoxy \
    && make install
